#!/usr/bin/python

# -*- coding: utf-8 -*-
"""
Created on Sun Apr  9 00:27:54 2017

@author: bineet
"""

uname='bineet'
passwd='nope'

from selenium import webdriver
from xvfbwrapper import Xvfb 
#
display= Xvfb()
display.start()

chromedriver = '/usr/local/src/niserauth/assets/chromedriver'
browser = webdriver.Chrome(chromedriver)
browser.get('https://172.16.255.254/login.html')

username = browser.find_element_by_name("username")
password = browser.find_element_by_name("password")

username.send_keys(uname)
password.send_keys(passwd)

browser.find_element_by_name("Submit").click()

browser.quit()
display.stop()
